graphhub/graphs/forms.py
from flask_wtf import FlaskForm
from flask_wtf.file import FileAllowed
from wtforms import StringField, SubmitField, TextAreaField, FileField
from wtforms.validators import DataRequired


class GraphForm(FlaskForm):
    name = StringField('Name', validators=[DataRequired()])
    tags = StringField('Tags')
    description = TextAreaField('Description', validators=[DataRequired()])
    project_file = FileField('Project file', validators=[FileAllowed(['gmom']), DataRequired()])
    submit = SubmitField('Submit')


class CommentForm(FlaskForm):
    text = TextAreaField('Add your comment', validators=[DataRequired()])
    submit = SubmitField('Comment')

graphhub/graphs/routes.py
from flask import (render_template, url_for, flash,
                   redirect, request, abort, Blueprint, send_file, jsonify)
from flask_login import current_user, login_required

from graphhub import db
from graphhub.graphs.forms import GraphForm, CommentForm
from graphhub.graphs.utils import save_project
from graphhub.models import Graph, Tag, Comment, Like

graphs = Blueprint('graphs', __name__)


@graphs.route("/graph/new", methods=['GET', 'POST'])
@login_required
def new_graph():
    form = GraphForm()
    if form.validate_on_submit():
        project_file = save_project(form.project_file.data)
        graph = Graph(name=form.name.data,
                      description=form.description.data,
                      author=current_user,
                      project_file=project_file)
        for tag_text in form.tags.data.split(','):
            tag = Tag.query.filter_by(text=tag_text).first()
            if not tag:
                tag = Tag(text=tag_text)
                db.session.add(tag)
            graph.tags.append(tag)
        db.session.add(graph)
        db.session.commit()
        flash('Your graph has been added!', 'success')
        return redirect(url_for('graphs.graph', graph_id=graph.id))
    return render_template('new_graph.html', title='New Graph',
                           form=form, legend='New Graph')


@graphs.route("/graph/<int:graph_id>", methods=['GET', 'POST'])
def graph(graph_id):
    graph = Graph.query.get_or_404(graph_id)
    form = CommentForm()
    if form.validate_on_submit():
        if current_user.is_authenticated:
            comment = Comment(text=form.text.data,
                              graph_id=graph.id,
                              author=current_user)
            db.session.add(comment)
            db.session.commit()
            flash('Your comment has been added!', 'success')
            return redirect(url_for('graphs.graph', graph_id=graph.id))
        else:
            flash('You must be logged in to comment!', 'danger')
            return redirect(url_for('graphs.graph', graph_id=graph.id))
    comments = Comment.query.filter_by(graph_id=graph.id)
    nr_comments = comments.count()
    comments = comments.all()
    nr_likes = Like.query.filter_by(graph_id=graph.id).count()
    if current_user.is_authenticated:
        liked = Like.query.filter_by(graph_id=graph.id).filter_by(user_id=current_user.id).count()
    else:
        liked = 0
    return render_template('graph.html', title=graph.name, graph=graph, comments=comments, nr_comments=nr_comments,
                           nr_likes=nr_likes, liked=liked, form=form)


@graphs.route("/graph/<int:graph_id>/download")
def download_graph(graph_id):
    graph = Graph.query.get_or_404(graph_id)
    graph.downloads = graph.downloads + 1
    db.session.commit()
    return send_file(graph.project_file, as_attachment=True,
                     attachment_filename=graph.name + '.gmom')


@graphs.route("/graph/<int:graph_id>/update", methods=['GET', 'POST'])
@login_required
def update_graph(graph_id):
    graph = Graph.query.get_or_404(graph_id)
    if graph.author != current_user:
        abort(403)
    form = GraphForm()
    if form.validate_on_submit():
        graph.name = form.name.data
        graph.description = form.description.data
        graph.project_file = save_project(form.project_file.data)
        graph.tags = []
        for tag_text in form.tags.data.split(','):
            tag = Tag.query.filter_by(text=tag_text).first()
            if not tag:
                tag = Tag(text=tag_text)
                db.session.add(tag)
            graph.tags.append(tag)
        db.session.commit()
        flash('Your post has been updated!', 'success')
        return redirect(url_for('graphs.graph', graph_id=graph.id))
    elif request.method == 'GET':
        form.name.data = graph.name
        form.description.data = graph.description
    return render_template('new_graph.html', title='Update graph',
                           form=form, legend='Update graph')


@graphs.route("/graph/<int:graph_id>/delete", methods=['POST'])
@login_required
def delete_graph(graph_id):
    graph = Graph.query.get_or_404(graph_id)
    if graph.author != current_user:
        abort(403)
    db.session.query(Comment).filter_by(graph_id=graph.id).delete()
    db.session.query(Like).filter_by(graph_id=graph.id).delete()
    db.session.delete(graph)
    db.session.commit()
    flash('Your graph has been deleted!', 'success')
    return redirect(url_for('main.browse'))


@graphs.route("/graph/like", methods=['GET', 'POST'])
def like_graph():
    if current_user.is_authenticated:
        graph_id = request.args.get('graph_id', None, type=int)
        Graph.query.get_or_404(graph_id)
        like = Like.query.filter_by(author=current_user).filter_by(graph_id=graph_id)
        if like.count() == 0:
            like = Like(graph_id=graph_id, author=current_user)
            db.session.add(like)
            db.session.commit()
            return jsonify(status=200, action='like')
        else:
            like.delete()
            db.session.commit()
        return jsonify(status=200, action='dislike')
    return jsonify(status=403)

graphhub/main/routes.py
from flask import render_template, request, Blueprint
from flask_login import current_user
from sqlalchemy import func

from graphhub import db
from graphhub.models import Graph, Tag, User, Comment, Like

main = Blueprint('main', __name__)


@main.route("/")
@main.route("/browse")
def browse():
    page = request.args.get('page', 1, type=int)
    filter_tags = request.args.getlist('filter_tags', None)
    filter_user = request.args.get('filter_user', None, type=int)
    order = request.args.get('order_by', 'date_added_desc')

    comments = db.session.query(Comment.graph_id, func.count(Comment.id).label('nr_comments')). \
        group_by(Comment.graph_id).subquery()

    likes = db.session.query(Like.graph_id, func.count(Like.id).label('nr_likes')). \
        group_by(Like.graph_id).subquery()

    if current_user.is_authenticated:
        liked = db.session.query(Like.graph_id, func.count(Like.id).label('liked')). \
            group_by(Like.graph_id).filter_by(user_id=current_user.id).subquery()
    else:
        liked = db.session.query(Like.graph_id, func.count(Like.id).label('liked')). \
            group_by(Like.graph_id).filter_by(user_id=None).subquery()

    graphs = db.session.query(Graph, comments.c.nr_comments, likes.c.nr_likes, liked.c.liked). \
        outerjoin(comments, Graph.id == comments.c.graph_id). \
        outerjoin(likes, Graph.id == likes.c.graph_id). \
        outerjoin(liked, Graph.id == liked.c.graph_id)

    if filter_tags:
        graphs = graphs.filter(Graph.tags.any(Tag.text.in_(filter_tags)))

    if filter_user:
        graphs = graphs.filter(Graph.user_id == filter_user)

    if order == 'date_added_desc':
        graphs = graphs.order_by(Graph.date_added.desc())
    elif order == 'date_added_asc':
        graphs = graphs.order_by(Graph.date_added.asc())
    elif order == 'likes_desc':
        graphs = graphs.order_by(likes.c.nr_likes.desc())
    elif order == 'likes_asc':
        graphs = graphs.order_by(likes.c.nr_likes.asc())

    graphs = graphs.paginate(page=page, per_page=5)

    tags = Tag.query.with_entities(Tag.text).distinct(Tag.text).order_by(Tag.text.asc()).all()

    users = User.query.with_entities(User.id, User.username).order_by(User.username.asc()).all()

    return render_template('browse.html', graphs=graphs, tags=tags, users=users,
                           order_by=order, filter_tags=filter_tags, filter_user=filter_user)


@main.route("/about")
def about():
    return render_template('about.html', title='About')

graphhub/users/routes.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required

from graphhub import db, bcrypt
from graphhub.models import User
from graphhub.users.forms import (RegistrationForm, LoginForm, UpdateAccountForm,
                                  RequestResetForm, ResetPasswordForm)
from graphhub.users.utils import save_picture, send_reset_email

users = Blueprint('users', __name__)


@users.route("/register", methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = RegistrationForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(user)
        db.session.commit()
        flash('Your account has been created! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


@users.route("/login", methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.browse'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.browse'))
        else:
            flash('Login Unsuccessful. Please check email and password', 'danger')
    return render_template('login.html', title='Login', form=form)


@users.route("/logout")
def logout():
    logout_user()
    return redirect(url_for('main.browse'))


@users.route("/account", methods=['GET', 'POST'])
@login_required
def account():
    form = UpdateAccountForm()
    if form.validate_on_submit():
        if form.picture.data:
            picture_file = save_picture(form.picture.data)
            current_user.image_file = picture_file
        current_user.username = form.username.data
        current_user.email = form.email.data
        db.session.commit()
        flash('Your account has been updated!', 'success')
        return redirect(url_for('users.account'))
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
    image_file = url_for('static', filename='profile_pics/' + current_user.image_file)
    return render_template('account.html', title='Account',
                           image_file=image_file, form=form)


@users.route("/reset_password", methods=['GET', 'POST'])
def reset_request():
    if current_user.is_authenticated:
        return redirect(url_for('main.browse'))
    form = RequestResetForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        send_reset_email(user)
        flash('An email has been sent with instructions to reset your password.', 'info')
        return redirect(url_for('users.login'))
    return render_template('reset_request.html', title='Reset Password', form=form)


@users.route("/reset_password/<token>", methods=['GET', 'POST'])
def reset_token(token):
    if current_user.is_authenticated:
        return redirect(url_for('main.browse'))
    user = User.verify_reset_token(token)
    if user is None:
        flash('That is an invalid or expired token', 'warning')
        return redirect(url_for('users.reset_request'))
    form = ResetPasswordForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        user.password = hashed_password
        db.session.commit()
        flash('Your password has been updated! You are now able to log in', 'success')
        return redirect(url_for('users.login'))
    return render_template('reset_token.html', title='Reset Password', form=form)

graphhub/templates/about.html
{% extends "layout.html" %}
{% block content %}
    <div class="card border-primary">
        <div class="card-body">
            <legend class="border-bottom mb-4">About GRAPH-hub</legend>
            <p>GRAPH-hub allows you to browse variety of GRAPH-moment projects created by other users. After
                registration you can upload your own projects and share them with others. Comment projects and make sure
                to leave a like reaction under the ones you appreciate.</p>
            <p>Don't know GRAPH-moment yet? Download it
                <a href=" {{ url_for('static',filename='graph_moment/GRAPH-moment-1.0.zip') }}" download>here</a>
                and check how quick you can build and generate random graphs visualisations. Learn more about it on
                <a href="https://github.com/mateuszpach/GRAPH-moment" download>Github</a>.
            </p>
            <p>GRAPH-hub is built by Mateusz Pach. Visit my
                <a href="https://www.linkedin.com/in/mateusz-pach/" download>LinkedIn</a>
                and
                <a href="https://github.com/mateuszpach/" download>Github</a>. Don't hesitate to reach out to me there.
            </p>
        </div>
    </div>
{% endblock content %}

graphhub/templates/account.html
{% extends "layout.html" %}
{% block content %}
    <div class="card border-primary">
        <div class="card-body">
            <div class="media">
                <img class="rounded-circle account-img" src="{{ image_file }}">
                <div class="media-body mt-5">
                    <h2 class="account-heading">{{ current_user.username }}</h2>
                    <p class="text-secondary">{{ current_user.email }}</p>
                </div>
            </div>
            <form method="POST" action="" enctype="multipart/form-data">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Account Info</legend>
                    <div class="form-group">
                        {{ form.username.label(class="form-control-label") }}

                        {% if form.username.errors %}
                            {{ form.username(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.username.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.username(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.email.label(class="form-control-label") }}
                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.picture.label() }}
                        {{ form.picture(class="form-control-file") }}
                        {% if form.picture.errors %}
                            {% for error in form.picture.errors %}
                                <span class="text-danger">{{ error }}</span></br>
                            {% endfor %}
                        {% endif %}
                    </div>
                </fieldset>
                <div class="form-group d-flex justify-content-end">
                    {{ form.submit(class="btn btn-primary") }}
                </div>
            </form>
        </div>
    </div>
{% endblock content %}

graphhub/templates/graph.html
{% extends "layout.html" %}
{% block content %}
    <article class="card border-primary mb-4">
        <div class="card-body">
            <div class="row">
                <div class="col">
                    <h5 class="card-title"><a
                            href="{{ url_for('graphs.graph', graph_id=graph.id) }}">{{ graph.name }}</a>
                    </h5>
                    <h6>
                        {% for tag in graph.tags %}
                            <a href="{{ url_for('main.browse', filter_tags=tag.text) }}">#{{ tag.text }}</a>
                        {% endfor %}
                    </h6>
                    <h6 class="text-muted">added {{ graph.date_added.strftime('%Y-%m-%d') }} by
                        <a href="{{ url_for('main.browse', filter_user=graph.user_id) }}">
                            {{ graph.author.username }}
                        </a>
                    </h6>
                </div>
                <div class="col-4 text-right text-muted mt-1">
                    <i class="fas fa-thumbs-up"></i> {{ nr_likes }}
                    <i class="fas fa-comment ml-2"></i> {{ nr_comments }}
                    <i class="fas fa-download ml-2"></i> {{ graph.downloads }}
                </div>
            </div>

            <p class="card-text"> {{ graph.description }} </p>

            <div class="row">
                <div class="col">
                    {% if liked == 0 %}
                        <button type="button" class="like btn btn-outline-primary" value="{{ graph.id }}">
                            <i class="fas fa-thumbs-up mr-2"></i>Like
                        </button>
                    {% else %}
                        <button type="button" class="like btn btn-outline-success" value="{{ graph.id }}">
                            <i class="fas fa-thumbs-up mr-2"></i>Liked
                        </button>
                    {% endif %}
                </div>
                <div class="col-4 d-flex justify-content-end">
                    {% if graph.author == current_user %}
                        <button type="button" class="btn btn-danger mr-2" data-toggle="modal"
                                data-target="#deleteModal">Delete
                        </button>
                        <a class="btn btn-primary mr-2"
                           href="{{ url_for('graphs.update_graph', graph_id=graph.id) }}">Update</a>
                    {% endif %}
                    <a href="{{ url_for('graphs.graph', graph_id=graph.id) }}/download"
                       class="btn btn-primary">
                        <i class="fas fa-download mr-2"></i>Download
                    </a>
                </div>
            </div>

            <!-- Comments -->
            <hr>
            <h5 class="">Comments</h5>
            <form method="POST" action="" enctype="multipart/form-data">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    {{ form.text.label(class="form-control-label") }}
                    {% if form.text.errors %}
                        {{ form.text(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.text.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.text(class="form-control form-control-lg") }}
                    {% endif %}
                </fieldset>
                <div class="form-group d-flex justify-content-end mb-4">
                    {{ form.submit(class="btn btn-sm btn-primary") }}
                </div>
            </form>
            {% for comment in comments %}
                <div class="media">
                    <img class="rounded-circle account-img-sm"
                         src="{{ url_for('static', filename='profile_pics/' + comment.author.image_file) }}">
                    <div class="media-body">
                        <div class="row">
                            <div class="col">
                                <h6 class="text-muted">
                                    <a class="mr-2" href="{{ url_for('main.browse', filter_user=comment.user_id) }}">
                                        {{ comment.author.username }}
                                    </a>
                                </h6>
                            </div>
                            <div class="col-4 d-flex justify-content-end text-muted">
                                {{ comment.date_added.strftime('%Y-%m-%d %-H:%I%p') }}
                            </div>
                        </div>

                        <p>{{ comment.text }}</p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </article>

    <!-- Modal -->
    <div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="deleteModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="deleteModalLabel">Delete graph?</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                    <form action="{{ url_for('graphs.delete_graph', graph_id=graph.id) }}" method="POST">
                        <input class="btn btn-danger" type="submit" value="Delete">
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

graphhub/templates/layout.html
<!DOCTYPE html>
<html>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel='shortcut icon' type='image/x-icon' href=' {{ url_for('static', filename='favicon.ico') }}'/>

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
          integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.14/css/bootstrap-select.min.css"
          rel="stylesheet"/>

    <!-- Font Awesome CSS -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.14.0/css/all.min.css"
          integrity="sha512-1PKOgIY59xJ8Co8+NE6FZ+LOAZKjy+KY8iq0G4B3CyeY6wYHN3yt9PW0XpSriVlkMXe40PTKnXrLnZ9+fkDaog=="
          crossorigin="anonymous"/>

    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='main.css') }}">

    {% if title %}
        <title>GRAPH hub - {{ title }}</title>
    {% else %}
        <title>GRAPH hub</title>
    {% endif %}
</head>
<body>
<header class="site-header">
    <nav class="navbar navbar-expand-md fixed-top navbar-dark bg-primary mb-4">
        <div class="container">
            <a class="navbar-brand mr-4" href="/">GRAPH hub</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle"
                    aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarToggle">
                <div class="navbar-nav mr-auto">
                    <a class="nav-item nav-link" href="{{ url_for('main.browse') }}">Browse</a>
                    {% if current_user.is_authenticated %}
                        <a class="nav-item nav-link" href="{{ url_for('main.browse', filter_user=current_user.id) }}">My
                            graphs</a>
                        <a class="nav-item nav-link" href="{{ url_for('graphs.new_graph') }}">Upload a graph</a>
                    {% endif %}
                    <a class="nav-item nav-link" href="{{ url_for('main.about') }}">About</a>
                </div>
                <!-- Navbar Right Side -->
                <div class="navbar-nav">
                    {% if current_user.is_authenticated %}
                        <a class="nav-item nav-link" href="{{ url_for('users.account') }}">Account</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.logout') }}">Logout</a>
                    {% else %}
                        <a class="nav-item nav-link" href="{{ url_for('users.login') }}">Login</a>
                        <a class="nav-item nav-link" href="{{ url_for('users.register') }}">Register</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
</header>
<main role="main" class="container">
    <div class="row">
        <div class="col-md" id="flash-container">
            {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                    {% for category, message in messages %}
                        <div class="alert alert-{{ category }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                {% endif %}
            {% endwith %}
        </div>
    </div>
    {% block content %}

    {% endblock %}
</main>

<!-- Optional JavaScript -->
<!-- jQuery first, then Popper.js, then Bootstrap JS, then custom -->
<script src="https://code.jquery.com/jquery-3.5.1.min.js"
        integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0="
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
        integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
        integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
        crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-select/1.13.14/js/bootstrap-select.min.js"></script>
<script type=text/javascript>
    $SCRIPT_ROOT = {{ request.script_root|tojson|safe }};
</script>
<script type="text/javascript" src=" {{ url_for('static', filename='main.js') }}"></script>
</body>
</html>

graphhub/templates/login.html
{% extends "layout.html" %}
{% block content %}
    <div class="card border-primary">
        <div class="card-body">
            <form method="POST" action="">
                {{ form.hidden_tag() }}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Log In</legend>
                    <div class="form-group">
                        {{ form.email.label(class="form-control-label") }}
                        {% if form.email.errors %}
                            {{ form.email(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.email.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.email(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-group">
                        {{ form.password.label(class="form-control-label") }}
                        {% if form.password.errors %}
                            {{ form.password(class="form-control form-control-lg is-invalid") }}
                            <div class="invalid-feedback">
                                {% for error in form.password.errors %}
                                    <span>{{ error }}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.password(class="form-control form-control-lg") }}
                        {% endif %}
                    </div>
                    <div class="form-check">
                        {{ form.remember(class="form-check-input") }}
                        {{ form.remember.label(class="form-check-label") }}
                    </div>
                </fieldset>

                <div class="row">
                    <div class="col-2">
                        <a class="btn btn-outline-primary" type="button" href="{{ url_for('users.reset_request') }}">
                            Forgot Password?
                        </a>
                    </div>
                    <div class="col">
                        <div class="form-group d-flex justify-content-end">
                            {{ form.submit(class="btn btn-primary") }}
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            Need An Account? <a class="ml-2" href="{{ url_for('users.register') }}">Sign Up Now</a>
        </small>
    </div>
{% endblock content %}

graphhub/templates/reset_request.html
{% extends "layout.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST" action="">
            {{ form.hidden_tag() }}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Reset Password</legend>
                <div class="form-group">
                    {{ form.email.label(class="form-control-label") }}
                    {% if form.email.errors %}
                        {{ form.email(class="form-control form-control-lg is-invalid") }}
                        <div class="invalid-feedback">
                            {% for error in form.email.errors %}
                                <span>{{ error }}</span>
                            {% endfor %}
                        </div>
                    {% else %}
                        {{ form.email(class="form-control form-control-lg") }}
                    {% endif %}
                </div>
            </fieldset>
            <div class="form-group d-flex justify-content-end">
                {{ form.submit(class="btn btn-primary") }}
            </div>
        </form>
    </div>
{% endblock content %}